In [1]:
import pandas as pd
import numpy as np
import os

## 1. Dataset selection & protocol analysis.

In [2]:
#organizing audio samples into training sets.
#creating a datframe named training_protocols.

training_protocols_path = "ASVspoof2019_LA_cm_protocols/ASVspoof2019.LA.cm.train.trn.txt"

training_protocols = pd.read_csv(training_protocols_path, sep=" ", header=None)
training_protocols.columns = ["speaker", "file_id", "attack", "channel", "label"]
training_protocols["split"] = "train"

#Adding paths of Audio files to dataframe according to their file_id s.

AUDIO_BASE = "ASVspoof2019_LA_train/flac/"

training_protocols["audio_path"] = training_protocols["file_id"].apply(
    lambda x: f"{AUDIO_BASE}{x}.flac"
)

In [3]:
print(training_protocols.describe())

print(training_protocols.sample(5))
training_protocols.info()
training_protocols.shape
training_protocols.describe(include="all")

#Verifying audio paths exist
training_protocols["file_exists"] = training_protocols["audio_path"].apply(
    lambda x: os.path.exists(x)
)
training_protocols["file_exists"].value_counts()


training_protocols[["audio_path", "label", "split"]].head()

        speaker       file_id attack channel  label  split  \
count     25380         25380  25380   25380  25380  25380
unique       20         25380      1       7      2      1
top     LA_0082  LA_T_1138215      -     A01  spoof  train
freq       1308             1  25380    3800  22800  25380

                                          audio_path
count                                          25380
unique                                         25380
top     ASVspoof2019_LA_train/flac/LA_T_1138215.flac
freq                                               1
       speaker       file_id attack channel     label  split  \
23887  LA_0091  LA_T_3526465      -     A06     spoof  train
23019  LA_0086  LA_T_6514299      -     A06     spoof  train
24155  LA_0092  LA_T_7032978      -     A06     spoof  train
5284   LA_0093  LA_T_3647945      -     A01     spoof  train
2003   LA_0094  LA_T_5716018      -       -  bonafide  train

                                         audio_path
23887  ASVspoof2019_LA_train/flac/LA_T_3526465.flac
23019  ASVspoof2019_LA_train/flac/LA_T_6514299.flac
24155  ASVspoof2019_LA_train/flac/LA_T_7032978.flac
5284   ASVspoof2019_LA_train/flac/LA_T_3647945.flac
2003   ASVspoof2019_LA_train/flac/LA_T_5716018.flac
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25380 entries, 0 to 25379
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   speaker     25380 non-null  object
 1   file_id     25380 non-null  object
 2   attack      25380 non-null  object
 3   channel     25380 non-null  object
 4   label       25380 non-null  object
 5   split       25380 non-null  object
 6   audio_path  25380 non-null  object
dtypes: object(7)
memory usage: 1.4+ MB

                                     audio_path     label  split
0  ASVspoof2019_LA_train/flac/LA_T_1138215.flac  bonafide  train
1  ASVspoof2019_LA_train/flac/LA_T_1271820.flac  bonafide  train
2  ASVspoof2019_LA_train/flac/LA_T_1272637.flac  bonafide  train
3  ASVspoof2019_LA_train/flac/LA_T_1276960.flac  bonafide  train
4  ASVspoof2019_LA_train/flac/LA_T_1341447.flac  bonafide  train

In [4]:
#organizing audio samples into validation sets.
#creating a datframe named validation_protocols.

validation_protocols_path = "ASVspoof2019_LA_cm_protocols/ASVspoof2019.LA.cm.dev.trl.txt"

validation_protocols = pd.read_csv(validation_protocols_path, sep=" ", header=None)
validation_protocols.columns = ["speaker", "file_id", "attack", "channel", "label"]
validation_protocols["split"] = "validation"

#Adding paths of Audio files to dataframe according to their file_id s.

AUDIO_BASE = "ASVspoof2019_LA_dev/flac/"

validation_protocols["audio_path"] = validation_protocols["file_id"].apply(
    lambda x: f"{AUDIO_BASE}{x}.flac"
)

In [5]:
print(validation_protocols.describe())

print(validation_protocols.sample(5))
validation_protocols.info()
validation_protocols.shape
validation_protocols.describe(include="all")

#Verifying audio paths exist
validation_protocols["file_exists"] = validation_protocols["audio_path"].apply(
    lambda x: os.path.exists(x)
)
validation_protocols["file_exists"].value_counts()


validation_protocols[["audio_path", "label", "split"]].head()

        speaker       file_id attack channel  label       split  \
count     24844         24844  24844   24844  24844       24844
unique       20         24844      1       7      2           1
top     LA_0069  LA_D_1047731      -     A01  spoof  validation
freq       2638             1  24844    3716  22296       24844

                                        audio_path
count                                        24844
unique                                       24844
top     ASVspoof2019_LA_dev/flac/LA_D_1047731.flac
freq                                             1
       speaker       file_id attack channel  label       split  \
10537  LA_0070  LA_D_5393733      -     A03  spoof  validation
21617  LA_0070  LA_D_3433833      -     A06  spoof  validation
17055  LA_0078  LA_D_2273204      -     A04  spoof  validation
21030  LA_0078  LA_D_7944465      -     A05  spoof  validation
5040   LA_0075  LA_D_7969951      -     A01  spoof  validation

                                       audio_path
10537  ASVspoof2019_LA_dev/flac/LA_D_5393733.flac
21617  ASVspoof2019_LA_dev/flac/LA_D_3433833.flac
17055  ASVspoof2019_LA_dev/flac/LA_D_2273204.flac
21030  ASVspoof2019_LA_dev/flac/LA_D_7944465.flac
5040   ASVspoof2019_LA_dev/flac/LA_D_7969951.flac
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24844 entries, 0 to 24843
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   speaker     24844 non-null  object
 1   file_id     24844 non-null  object
 2   attack      24844 non-null  object
 3   channel     24844 non-null  object
 4   label       24844 non-null  object
 5   split       24844 non-null  object
 6   audio_path  24844 non-null  object
dtypes: object(7)
memory usage: 1.3+ MB

                                   audio_path     label       split
0  ASVspoof2019_LA_dev/flac/LA_D_1047731.flac  bonafide  validation
1  ASVspoof2019_LA_dev/flac/LA_D_1105538.flac  bonafide  validation
2  ASVspoof2019_LA_dev/flac/LA_D_1125976.flac  bonafide  validation
3  ASVspoof2019_LA_dev/flac/LA_D_1293230.flac  bonafide  validation
4  ASVspoof2019_LA_dev/flac/LA_D_1340209.flac  bonafide  validation

In [6]:
#organizing audio samples into testing sets.
#creating a datframe named testing_protocols.

testing_protocols_path = "ASVspoof2019_LA_cm_protocols/ASVspoof2019.LA.cm.eval.trl.txt"

testing_protocols = pd.read_csv(testing_protocols_path, sep=" ", header=None)
testing_protocols.columns = ["speaker", "file_id", "attack", "channel", "label"]
testing_protocols["split"] = "test"

#Adding paths of Audio files to dataframe according to their file_id s.

AUDIO_BASE = "ASVspoof2019_LA_eval/flac/"

testing_protocols["audio_path"] = testing_protocols["file_id"].apply(
    lambda x: f"{AUDIO_BASE}{x}.flac"
)

In [7]:
print(testing_protocols.describe())

print(testing_protocols.sample(5))
testing_protocols.info()
testing_protocols.shape
testing_protocols.describe(include="all")

#Verifying audio paths exist
testing_protocols["file_exists"] = testing_protocols["audio_path"].apply(
    lambda x: os.path.exists(x)
)
testing_protocols["file_exists"].value_counts()


testing_protocols[["audio_path", "label", "split"]].head()

        speaker       file_id attack channel  label  split  \
count     71237         71237  71237   71237  71237  71237
unique       67         71237      1      14      2      1
top     LA_0039  LA_E_2834763      -       -  spoof   test
freq       1784             1  71237    7355  63882  71237

                                         audio_path
count                                         71237
unique                                        71237
top     ASVspoof2019_LA_eval/flac/LA_E_2834763.flac
freq                                              1
       speaker       file_id attack channel     label split  \
40730  LA_0017  LA_E_4983860      -     A10     spoof  test
9754   LA_0024  LA_E_8551052      -       -  bonafide  test
45402  LA_0042  LA_E_9621625      -     A07     spoof  test
43067  LA_0016  LA_E_3249103      -     A16     spoof  test
21509  LA_0027  LA_E_2479762      -     A07     spoof  test

                                        audio_path
40730  ASVspoof2019_LA_eval/flac/LA_E_4983860.flac
9754   ASVspoof2019_LA_eval/flac/LA_E_8551052.flac
45402  ASVspoof2019_LA_eval/flac/LA_E_9621625.flac
43067  ASVspoof2019_LA_eval/flac/LA_E_3249103.flac
21509  ASVspoof2019_LA_eval/flac/LA_E_2479762.flac
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71237 entries, 0 to 71236
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   speaker     71237 non-null  object
 1   file_id     71237 non-null  object
 2   attack      71237 non-null  object
 3   channel     71237 non-null  object
 4   label       71237 non-null  object
 5   split       71237 non-null  object
 6   audio_path  71237 non-null  object
dtypes: object(7)
memory usage: 3.8+ MB

                                    audio_path  label split
0  ASVspoof2019_LA_eval/flac/LA_E_2834763.flac  spoof  test
1  ASVspoof2019_LA_eval/flac/LA_E_8877452.flac  spoof  test
2  ASVspoof2019_LA_eval/flac/LA_E_6828287.flac  spoof  test
3  ASVspoof2019_LA_eval/flac/LA_E_6977360.flac  spoof  test
4  ASVspoof2019_LA_eval/flac/LA_E_5932896.flac  spoof  test

## 2. Audio Preprocessing Pipeline.