In [1]:
import pandas as pd
import numpy as np
import os
import librosa

## Dataset selection & protocol analysis.

In [2]:
# organizing audio samples into training sets.
# creating a datframe named training_protocols.

training_protocols_path = "ASVspoof2019_LA_cm_protocols/ASVspoof2019.LA.cm.train.trn.txt"

training_protocols = pd.read_csv(training_protocols_path, sep=" ", header=None)
training_protocols.columns = ["speaker", "file_id", "attack", "channel", "label"]
training_protocols["split"] = "train"

# Adding paths of Audio files to dataframe according to their file_id s.

AUDIO_BASE = "ASVspoof2019_LA_train/flac/"

training_protocols["audio_path"] = training_protocols["file_id"].apply(
    lambda x: f"{AUDIO_BASE}{x}.flac"
)

In [3]:
# Verifying audio paths exist.
training_protocols["file_exists"] = training_protocols["audio_path"].apply(
    lambda x: os.path.exists(x)
)
training_protocols["file_exists"].value_counts()

file_exists
True    25380
Name: count, dtype: int64

In [4]:
training_protocols.describe(include="all")

,speaker,file_id,attack,channel,label,split,audio_path,file_exists
count,25380,25380,25380,25380,25380,25380,25380,25380
unique,20,25380,1,7,2,1,25380,1
top,LA_0082,LA_T_1138215,-,A01,spoof,train,ASVspoof2019_LA_train/flac/LA_T_1138215.flac,True
freq,1308,1,25380,3800,22800,25380,1,25380

In [5]:
training_protocols["label"].value_counts()

label
spoof       22800
bonafide     2580
Name: count, dtype: int64

In [6]:
training_protocols[["audio_path", "label", "split"]].head()

                                     audio_path     label  split
0  ASVspoof2019_LA_train/flac/LA_T_1138215.flac  bonafide  train
1  ASVspoof2019_LA_train/flac/LA_T_1271820.flac  bonafide  train
2  ASVspoof2019_LA_train/flac/LA_T_1272637.flac  bonafide  train
3  ASVspoof2019_LA_train/flac/LA_T_1276960.flac  bonafide  train
4  ASVspoof2019_LA_train/flac/LA_T_1341447.flac  bonafide  train

In [7]:
# organizing audio samples into validation sets.
# creating a datframe named validation_protocols.

validation_protocols_path = "ASVspoof2019_LA_cm_protocols/ASVspoof2019.LA.cm.dev.trl.txt"

validation_protocols = pd.read_csv(validation_protocols_path, sep=" ", header=None)
validation_protocols.columns = ["speaker", "file_id", "attack", "channel", "label"]
validation_protocols["split"] = "validation"

# Adding paths of Audio files to dataframe according to their file_id s.

AUDIO_BASE = "ASVspoof2019_LA_dev/flac/"

validation_protocols["audio_path"] = validation_protocols["file_id"].apply(
    lambda x: f"{AUDIO_BASE}{x}.flac"
)

In [8]:
# Verifying audio paths exist.
validation_protocols["file_exists"] = validation_protocols["audio_path"].apply(
    lambda x: os.path.exists(x)
)
validation_protocols["file_exists"].value_counts()

file_exists
True    24844
Name: count, dtype: int64

In [9]:
validation_protocols.describe(include="all")

,speaker,file_id,attack,channel,label,split,audio_path,file_exists
count,24844,24844,24844,24844,24844,24844,24844,24844
unique,20,24844,1,7,2,1,24844,1
top,LA_0069,LA_D_1047731,-,A01,spoof,validation,ASVspoof2019_LA_dev/flac/LA_D_1047731.flac,True
freq,2638,1,24844,3716,22296,24844,1,24844

In [10]:
validation_protocols["label"].value_counts()

label
spoof       22296
bonafide     2548
Name: count, dtype: int64

In [11]:
validation_protocols[["audio_path", "label", "split"]].head()

                                   audio_path     label       split
0  ASVspoof2019_LA_dev/flac/LA_D_1047731.flac  bonafide  validation
1  ASVspoof2019_LA_dev/flac/LA_D_1105538.flac  bonafide  validation
2  ASVspoof2019_LA_dev/flac/LA_D_1125976.flac  bonafide  validation
3  ASVspoof2019_LA_dev/flac/LA_D_1293230.flac  bonafide  validation
4  ASVspoof2019_LA_dev/flac/LA_D_1340209.flac  bonafide  validation

In [12]:
# organizing audio samples into testing sets.
# creating a datframe named testing_protocols.

testing_protocols_path = "ASVspoof2019_LA_cm_protocols/ASVspoof2019.LA.cm.eval.trl.txt"

testing_protocols = pd.read_csv(testing_protocols_path, sep=" ", header=None)
testing_protocols.columns = ["speaker", "file_id", "attack", "channel", "label"]
testing_protocols["split"] = "test"

# Adding paths of Audio files to dataframe according to their file_id s.

AUDIO_BASE = "ASVspoof2019_LA_eval/flac/"

testing_protocols["audio_path"] = testing_protocols["file_id"].apply(
    lambda x: f"{AUDIO_BASE}{x}.flac"
)

In [13]:
# Verifying audio paths exist.
testing_protocols["file_exists"] = testing_protocols["audio_path"].apply(
    lambda x: os.path.exists(x)
)
testing_protocols["file_exists"].value_counts()

file_exists
True    71237
Name: count, dtype: int64

In [14]:
testing_protocols.describe(include="all")

,speaker,file_id,attack,channel,label,split,audio_path,file_exists
count,71237,71237,71237,71237,71237,71237,71237,71237
unique,67,71237,1,14,2,1,71237,1
top,LA_0039,LA_E_2834763,-,-,spoof,test,ASVspoof2019_LA_eval/flac/LA_E_2834763.flac,True
freq,1784,1,71237,7355,63882,71237,1,71237

In [15]:
testing_protocols["label"].value_counts()

label
spoof       63882
bonafide     7355
Name: count, dtype: int64

In [16]:
testing_protocols[["audio_path", "label", "split"]].head()

                                    audio_path  label split
0  ASVspoof2019_LA_eval/flac/LA_E_2834763.flac  spoof  test
1  ASVspoof2019_LA_eval/flac/LA_E_8877452.flac  spoof  test
2  ASVspoof2019_LA_eval/flac/LA_E_6828287.flac  spoof  test
3  ASVspoof2019_LA_eval/flac/LA_E_6977360.flac  spoof  test
4  ASVspoof2019_LA_eval/flac/LA_E_5932896.flac  spoof  test

In [17]:
# 1. Audio preprocessing pipeline.

def audio_preprocessing_pipeline(audio_path, target_sr=22050, target_duration=4.0):
                                     
    target_length = int(target_sr * target_duration)
    
    # Loading & resampling.
    audio, _ = librosa.load(audio_path, sr=target_sr)
    
    # Normalizing.
    audio = librosa.util.normalize(audio)
    
    # Trimming silence.
    audio, _ = librosa.effects.trim(audio)
    
    # Padding or cropping(if any).
    if len(audio) < target_length:
        audio = np.pad(audio, (0, target_length - len(audio)))
    else:
        audio = audio[:target_length]
    
    return audio

# 2. Feature extraction pipeline to generate MFCC feature vectors.

def extract_mfcc_features(
    audio,
    sr=22050,
    n_mfcc=13
):    
    """
    Function Parameters:
        - audio:(output of preprocessing pipeline)
        - sr: sample rate (default 16kHz)
        - n_mfcc: number of MFCC coefficients
    """
    # Extracting MFCCs.
    mfccs = librosa.feature.mfcc(y=audio, n_mfcc=n_mfcc, sr=sr)
    
    # Extracting first / second MFCCs drivatives.
    delta_mfccs = librosa.feature.delta(mfccs)
    delta2_mfccs = librosa.feature.delta(mfccs, order=2)
    #print(mfccs.shape)
    #print(delta_mfccs.shape)
    #print(delta2_mfccs.shape)
    
    mfccs_features_combined = np.vstack([mfccs, delta_mfccs, delta2_mfccs])
    #print(mfccs_features_combined.shape)
    
    # Right now mfccs_features_combined.shape is (39, T), that's a 2d array having time as also a variable,
    # but classical ML models wants fixed lenght vectors or we as 1d arrays example: (78,).
    # For this we will take mean and standard deviation of mfccs_features_combined over duration of audio file (4 secs),
    # and pool them together into one vector of shape (78,) that we can feed into our model.
    
    mfcc_mean = np.mean(mfccs_features_combined, axis=1)
    mfcc_std = np.std(mfccs_features_combined, axis=1)
    
    # Hence MFCC feature vector is created.
    feature_vector = np.concatenate([mfcc_mean, mfcc_std])
    #print(feature_vector.shape)
    
    return feature_vector

## Feature Creation.

In [18]:
def full_audio_processing(
    audio_path,
    target_sr=22050,
    target_duration=4.0,
    n_mfcc=13
):
    # Audio preprocessing.
    audio = audio_preprocessing_pipeline(
        audio_path=audio_path,
        target_sr=target_sr,
        target_duration=target_duration
    )

    # MFCC + Delta + Delta-Delta features extraction.
    feature_vector = extract_mfcc_features(
        audio=audio,
        sr=target_sr,
        n_mfcc=n_mfcc
    )

    return feature_vector

In [26]:
label_map = {"bonafide": 0, "spoof": 1}
training_protocols["label_enc"] = training_protocols["label"].map(label_map)
validation_protocols["label_enc"] = validation_protocols["label"].map(label_map)
testing_protocols["label_enc"] = testing_protocols["label"].map(label_map)

training_protocols[["audio_path", "label", "split", "label_enc"]].head()

                                     audio_path     label  split  label_enc
0  ASVspoof2019_LA_train/flac/LA_T_1138215.flac  bonafide  train          0
1  ASVspoof2019_LA_train/flac/LA_T_1271820.flac  bonafide  train          0
2  ASVspoof2019_LA_train/flac/LA_T_1272637.flac  bonafide  train          0
3  ASVspoof2019_LA_train/flac/LA_T_1276960.flac  bonafide  train          0
4  ASVspoof2019_LA_train/flac/LA_T_1341447.flac  bonafide  train          0

In [27]:
validation_protocols[["audio_path", "label", "split", "label_enc"]].head()

                                   audio_path     label       split  label_enc
0  ASVspoof2019_LA_dev/flac/LA_D_1047731.flac  bonafide  validation          0
1  ASVspoof2019_LA_dev/flac/LA_D_1105538.flac  bonafide  validation          0
2  ASVspoof2019_LA_dev/flac/LA_D_1125976.flac  bonafide  validation          0
3  ASVspoof2019_LA_dev/flac/LA_D_1293230.flac  bonafide  validation          0
4  ASVspoof2019_LA_dev/flac/LA_D_1340209.flac  bonafide  validation          0

In [28]:
testing_protocols[["audio_path", "label", "split", "label_enc"]].head()

                                    audio_path  label split  label_enc
0  ASVspoof2019_LA_eval/flac/LA_E_2834763.flac  spoof  test          1
1  ASVspoof2019_LA_eval/flac/LA_E_8877452.flac  spoof  test          1
2  ASVspoof2019_LA_eval/flac/LA_E_6828287.flac  spoof  test          1
3  ASVspoof2019_LA_eval/flac/LA_E_6977360.flac  spoof  test          1
4  ASVspoof2019_LA_eval/flac/LA_E_5932896.flac  spoof  test          1

In [29]:
from sklearn.linear_model import LogisticRegression

In [ ]:
lr = sklearn.linear_model.LogisticRegression()